
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>zfit.util.exception module &#8212; zfit 0.5.6.dev6+gaeab4d0 documentation</title>
    
  <link rel="stylesheet" href="../_static/css/index.73d71520a4ca3b99cfee5594769eaaae.css">

    
  <link rel="stylesheet"
    href="../_static/vendor/fontawesome/5.13.0/css/all.min.css">
  <link rel="preload" as="font" type="font/woff2" crossorigin
    href="../_static/vendor/fontawesome/5.13.0/webfonts/fa-solid-900.woff2">
  <link rel="preload" as="font" type="font/woff2" crossorigin
    href="../_static/vendor/fontawesome/5.13.0/webfonts/fa-brands-400.woff2">

    
      
  <link rel="stylesheet"
    href="../_static/vendor/open-sans_all/1.44.1/index.css">
  <link rel="stylesheet"
    href="../_static/vendor/lato_latin-ext/1.44.1/index.css">

    
    <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
    <link rel="stylesheet" href="../_static/basic.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="../_static/copybutton.css" />
    <link rel="stylesheet" type="text/css" href="../_static/css/custom.css" />
    
  <link rel="preload" as="script" href="../_static/js/index.3da636dd464baa7582d2.js">

    <script id="documentation_options" data-url_root="../" src="../_static/documentation_options.js"></script>
    <script src="../_static/jquery.js"></script>
    <script src="../_static/underscore.js"></script>
    <script src="../_static/doctools.js"></script>
    <script src="../_static/language_data.js"></script>
    <script src="../_static/clipboard.min.js"></script>
    <script src="../_static/copybutton.js"></script>
    <script async="async" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <link rel="shortcut icon" href="../_static/zfit-favicon.png"/>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="docsearch:language" content="en" />
  </head>
  <body data-spy="scroll" data-target="#bd-toc-nav" data-offset="80">
    
    <nav class="navbar navbar-light navbar-expand-lg bg-light fixed-top bd-navbar" id="navbar-main">
<div class="container-xl">

    <a class="navbar-brand" href="../index.html">
    
      <img src="../_static/zfit-logo-light_400x168.png" class="logo" alt="logo" />
    
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-menu" aria-controls="navbar-menu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navbar-menu" class="col-lg-9 collapse navbar-collapse">
      <ul id="navbar-main-elements" class="navbar-nav mr-auto">
        
        
        <li class="nav-item ">
            <a class="nav-link" href="../whats_new/index.html">What’s new?</a>
        </li>
        
        <li class="nav-item ">
            <a class="nav-link" href="../getting_started/index.html">Getting started</a>
        </li>
        
        <li class="nav-item ">
            <a class="nav-link" href="../user_api/index.html">API reference</a>
        </li>
        
        <li class="nav-item ">
            <a class="nav-link" href="../project/index.html">Project</a>
        </li>
        
        <li class="nav-item ">
            <a class="nav-link" href="../ask_a_question.html">Ask a question</a>
        </li>
        
        
      </ul>


      

      <ul class="navbar-nav">
        
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/zfit/zfit" target="_blank" rel="noopener">
              <span><i class="fab fa-github-square"></i></span>
            </a>
          </li>
        
        
      </ul>
    </div>
</div>
    </nav>
    

    <div class="container-xl">
      <div class="row">
          
          <div class="col-12 col-md-3 bd-sidebar"><form class="bd-search d-flex align-items-center" action="../search.html" method="get">
  <i class="icon fas fa-search"></i>
  <input type="search" class="form-control" name="q" id="search-input" placeholder="Search zfit..." aria-label="Search zfit..." autocomplete="off" >
</form>
<nav class="bd-links" id="bd-docs-nav" aria-label="Main navigation">

    <div class="bd-toc-item active">
    
  
    <ul class="nav bd-sidenav">
        
        
        
        
        
        
        
        
        
        
        
      </ul>
  
  </nav>
          </div>
          

          
          <div class="d-none d-xl-block col-xl-2 bd-toc">
              

<nav id="bd-toc-nav">
    <ul class="nav section-nav flex-column">
    
    </ul>
</nav>



<div class="tocsection editthispage">
    <a href="https://github.com/zfit/zfit/edit/develop/docs/full_api/zfit.util.exception.rst">
        <i class="fas fa-pencil-alt"></i> Edit this page
    </a>
</div>

              
          </div>
          

          
          <main class="col-12 col-md-9 col-xl-7 py-md-5 pl-md-5 pr-md-4 bd-content" role="main">
              
              <div>
                
  <div class="section" id="module-zfit.util.exception">
<span id="zfit-util-exception-module"></span><h1>zfit.util.exception module<a class="headerlink" href="#module-zfit.util.exception" title="Permalink to this headline">¶</a></h1>
<dl class="py exception">
<dt id="zfit.util.exception.PDFCompatibilityError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">PDFCompatibilityError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#PDFCompatibilityError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.PDFCompatibilityError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.PDFCompatibilityError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.PDFCompatibilityError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.PDFCompatibilityError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.PDFCompatibilityError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.LogicalUndefinedOperationError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">LogicalUndefinedOperationError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#LogicalUndefinedOperationError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.LogicalUndefinedOperationError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.LogicalUndefinedOperationError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.LogicalUndefinedOperationError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.LogicalUndefinedOperationError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.LogicalUndefinedOperationError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.OperationNotAllowedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">OperationNotAllowedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#OperationNotAllowedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.OperationNotAllowedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.OperationNotAllowedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.OperationNotAllowedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.OperationNotAllowedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.OperationNotAllowedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.ExtendedPDFError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">ExtendedPDFError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#ExtendedPDFError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.ExtendedPDFError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.ExtendedPDFError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.ExtendedPDFError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.ExtendedPDFError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.ExtendedPDFError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.AlreadyExtendedPDFError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">AlreadyExtendedPDFError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#AlreadyExtendedPDFError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.AlreadyExtendedPDFError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.ExtendedPDFError" title="zfit.util.exception.ExtendedPDFError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.ExtendedPDFError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.AlreadyExtendedPDFError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.AlreadyExtendedPDFError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.AlreadyExtendedPDFError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.AlreadyExtendedPDFError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.NotExtendedPDFError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">NotExtendedPDFError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#NotExtendedPDFError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.NotExtendedPDFError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.ExtendedPDFError" title="zfit.util.exception.ExtendedPDFError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.ExtendedPDFError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.NotExtendedPDFError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.NotExtendedPDFError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.NotExtendedPDFError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.NotExtendedPDFError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.ConversionError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">ConversionError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#ConversionError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.ConversionError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.ConversionError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.ConversionError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.ConversionError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.ConversionError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.SubclassingError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">SubclassingError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#SubclassingError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.SubclassingError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.SubclassingError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.SubclassingError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.SubclassingError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.SubclassingError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.BasePDFSubclassingError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">BasePDFSubclassingError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#BasePDFSubclassingError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.BasePDFSubclassingError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.SubclassingError" title="zfit.util.exception.SubclassingError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.SubclassingError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.BasePDFSubclassingError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.BasePDFSubclassingError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.BasePDFSubclassingError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.BasePDFSubclassingError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.IntentionAmbiguousError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">IntentionAmbiguousError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#IntentionAmbiguousError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.IntentionAmbiguousError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.IntentionAmbiguousError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.IntentionAmbiguousError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.IntentionAmbiguousError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.IntentionAmbiguousError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.UnderdefinedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">UnderdefinedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#UnderdefinedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.UnderdefinedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IntentionAmbiguousError" title="zfit.util.exception.IntentionAmbiguousError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IntentionAmbiguousError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.UnderdefinedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.UnderdefinedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.UnderdefinedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.UnderdefinedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.LimitsUnderdefinedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">LimitsUnderdefinedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#LimitsUnderdefinedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.LimitsUnderdefinedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.UnderdefinedError" title="zfit.util.exception.UnderdefinedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.UnderdefinedError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.LimitsUnderdefinedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.LimitsUnderdefinedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.LimitsUnderdefinedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.LimitsUnderdefinedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.NormRangeUnderdefinedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">NormRangeUnderdefinedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#NormRangeUnderdefinedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.NormRangeUnderdefinedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.UnderdefinedError" title="zfit.util.exception.UnderdefinedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.UnderdefinedError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.NormRangeUnderdefinedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.NormRangeUnderdefinedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.NormRangeUnderdefinedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.NormRangeUnderdefinedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.OverdefinedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">OverdefinedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#OverdefinedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.OverdefinedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IntentionAmbiguousError" title="zfit.util.exception.IntentionAmbiguousError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IntentionAmbiguousError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.OverdefinedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.OverdefinedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.OverdefinedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.OverdefinedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.LimitsOverdefinedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">LimitsOverdefinedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#LimitsOverdefinedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.LimitsOverdefinedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.OverdefinedError" title="zfit.util.exception.OverdefinedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.OverdefinedError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.LimitsOverdefinedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.LimitsOverdefinedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.LimitsOverdefinedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.LimitsOverdefinedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.CoordinatesUnderdefinedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">CoordinatesUnderdefinedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#CoordinatesUnderdefinedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.CoordinatesUnderdefinedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.UnderdefinedError" title="zfit.util.exception.UnderdefinedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.UnderdefinedError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.CoordinatesUnderdefinedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.CoordinatesUnderdefinedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.CoordinatesUnderdefinedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.CoordinatesUnderdefinedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.AxesAmbiguousError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">AxesAmbiguousError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#AxesAmbiguousError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.AxesAmbiguousError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IntentionAmbiguousError" title="zfit.util.exception.IntentionAmbiguousError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IntentionAmbiguousError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.AxesAmbiguousError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.AxesAmbiguousError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.AxesAmbiguousError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.AxesAmbiguousError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.NotSpecifiedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">NotSpecifiedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#NotSpecifiedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.NotSpecifiedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.NotSpecifiedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.NotSpecifiedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.NotSpecifiedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.NotSpecifiedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.LimitsNotSpecifiedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">LimitsNotSpecifiedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#LimitsNotSpecifiedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.LimitsNotSpecifiedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.NotSpecifiedError" title="zfit.util.exception.NotSpecifiedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.NotSpecifiedError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.LimitsNotSpecifiedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.LimitsNotSpecifiedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.LimitsNotSpecifiedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.LimitsNotSpecifiedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.NormRangeNotSpecifiedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">NormRangeNotSpecifiedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#NormRangeNotSpecifiedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.NormRangeNotSpecifiedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.NotSpecifiedError" title="zfit.util.exception.NotSpecifiedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.NotSpecifiedError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.NormRangeNotSpecifiedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.NormRangeNotSpecifiedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.NormRangeNotSpecifiedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.NormRangeNotSpecifiedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.AxesNotSpecifiedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">AxesNotSpecifiedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#AxesNotSpecifiedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.AxesNotSpecifiedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.NotSpecifiedError" title="zfit.util.exception.NotSpecifiedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.NotSpecifiedError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.AxesNotSpecifiedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.AxesNotSpecifiedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.AxesNotSpecifiedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.AxesNotSpecifiedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.ObsNotSpecifiedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">ObsNotSpecifiedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#ObsNotSpecifiedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.ObsNotSpecifiedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.NotSpecifiedError" title="zfit.util.exception.NotSpecifiedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.NotSpecifiedError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.ObsNotSpecifiedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.ObsNotSpecifiedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.ObsNotSpecifiedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.ObsNotSpecifiedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.NameAlreadyTakenError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">NameAlreadyTakenError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#NameAlreadyTakenError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.NameAlreadyTakenError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.NameAlreadyTakenError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.NameAlreadyTakenError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.NameAlreadyTakenError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.NameAlreadyTakenError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.IncompatibleError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">IncompatibleError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#IncompatibleError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.IncompatibleError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.IncompatibleError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.IncompatibleError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.IncompatibleError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.IncompatibleError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.ShapeIncompatibleError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">ShapeIncompatibleError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#ShapeIncompatibleError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.ShapeIncompatibleError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IncompatibleError" title="zfit.util.exception.IncompatibleError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IncompatibleError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.ShapeIncompatibleError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.ShapeIncompatibleError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.ShapeIncompatibleError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.ShapeIncompatibleError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.ObsIncompatibleError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">ObsIncompatibleError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#ObsIncompatibleError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.ObsIncompatibleError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IncompatibleError" title="zfit.util.exception.IncompatibleError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IncompatibleError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.ObsIncompatibleError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.ObsIncompatibleError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.ObsIncompatibleError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.ObsIncompatibleError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.AxesIncompatibleError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">AxesIncompatibleError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#AxesIncompatibleError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.AxesIncompatibleError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IncompatibleError" title="zfit.util.exception.IncompatibleError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IncompatibleError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.AxesIncompatibleError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.AxesIncompatibleError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.AxesIncompatibleError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.AxesIncompatibleError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.CoordinatesIncompatibleError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">CoordinatesIncompatibleError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#CoordinatesIncompatibleError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.CoordinatesIncompatibleError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IncompatibleError" title="zfit.util.exception.IncompatibleError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IncompatibleError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.CoordinatesIncompatibleError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.CoordinatesIncompatibleError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.CoordinatesIncompatibleError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.CoordinatesIncompatibleError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.SpaceIncompatibleError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">SpaceIncompatibleError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#SpaceIncompatibleError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.SpaceIncompatibleError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IncompatibleError" title="zfit.util.exception.IncompatibleError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IncompatibleError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.SpaceIncompatibleError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.SpaceIncompatibleError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.SpaceIncompatibleError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.SpaceIncompatibleError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.LimitsIncompatibleError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">LimitsIncompatibleError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#LimitsIncompatibleError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.LimitsIncompatibleError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IncompatibleError" title="zfit.util.exception.IncompatibleError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IncompatibleError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.LimitsIncompatibleError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.LimitsIncompatibleError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.LimitsIncompatibleError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.LimitsIncompatibleError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.NumberOfEventsIncompatibleError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">NumberOfEventsIncompatibleError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#NumberOfEventsIncompatibleError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.NumberOfEventsIncompatibleError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.ShapeIncompatibleError" title="zfit.util.exception.ShapeIncompatibleError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.ShapeIncompatibleError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.NumberOfEventsIncompatibleError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.NumberOfEventsIncompatibleError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.NumberOfEventsIncompatibleError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.NumberOfEventsIncompatibleError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.InvalidLimitSubspaceError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">InvalidLimitSubspaceError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#InvalidLimitSubspaceError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.InvalidLimitSubspaceError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.InvalidLimitSubspaceError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.InvalidLimitSubspaceError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.InvalidLimitSubspaceError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.InvalidLimitSubspaceError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.ModelIncompatibleError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">ModelIncompatibleError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#ModelIncompatibleError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.ModelIncompatibleError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.IncompatibleError" title="zfit.util.exception.IncompatibleError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.IncompatibleError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.ModelIncompatibleError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.ModelIncompatibleError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.ModelIncompatibleError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.ModelIncompatibleError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.WeightsNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">WeightsNotImplementedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#WeightsNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.WeightsNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.WeightsNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.WeightsNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.WeightsNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.WeightsNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.DataIsBatchedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">DataIsBatchedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#DataIsBatchedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.DataIsBatchedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.DataIsBatchedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.DataIsBatchedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.DataIsBatchedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.DataIsBatchedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.ParameterNotIndependentError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">ParameterNotIndependentError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#ParameterNotIndependentError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.ParameterNotIndependentError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.ParameterNotIndependentError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.ParameterNotIndependentError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.ParameterNotIndependentError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.ParameterNotIndependentError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.NotMinimizedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">NotMinimizedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#NotMinimizedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.NotMinimizedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.NotMinimizedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.NotMinimizedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.NotMinimizedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.NotMinimizedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.IllegalInGraphModeError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">IllegalInGraphModeError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#IllegalInGraphModeError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.IllegalInGraphModeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.IllegalInGraphModeError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.IllegalInGraphModeError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.IllegalInGraphModeError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.IllegalInGraphModeError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.CannotConvertToNumpyError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">CannotConvertToNumpyError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#CannotConvertToNumpyError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.CannotConvertToNumpyError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.CannotConvertToNumpyError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.CannotConvertToNumpyError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.CannotConvertToNumpyError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.CannotConvertToNumpyError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.ZfitNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">ZfitNotImplementedError</code><span class="sig-paren">(</span><em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#ZfitNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.ZfitNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#NotImplementedError" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">NotImplementedError</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.ZfitNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.ZfitNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.ZfitNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.ZfitNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.FunctionNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">FunctionNotImplementedError</code><span class="sig-paren">(</span><em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#FunctionNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.FunctionNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.ZfitNotImplementedError" title="zfit.util.exception.ZfitNotImplementedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.ZfitNotImplementedError</span></code></a></p>
<p>Any function, e.g. in a BaseModel, that not implemented and a fallback should be called.</p>
<p>Preferably use more specific exceptions</p>
<dl class="py attribute">
<dt id="zfit.util.exception.FunctionNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.FunctionNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.FunctionNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.FunctionNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.StandardControlFlow">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">StandardControlFlow</code><a class="reference internal" href="../_modules/zfit/util/exception.html#StandardControlFlow"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.StandardControlFlow" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<p>An exception that inherits from this class will be regarded as part of the standard control flow
and not as an Error. For example, if a function raises that values are NaN, this is often intercepted
on purpose.</p>
<dl class="py attribute">
<dt id="zfit.util.exception.StandardControlFlow.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.StandardControlFlow.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.StandardControlFlow.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.StandardControlFlow.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.SpecificFunctionNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">SpecificFunctionNotImplementedError</code><span class="sig-paren">(</span><em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#SpecificFunctionNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.SpecificFunctionNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.FunctionNotImplementedError" title="zfit.util.exception.FunctionNotImplementedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.FunctionNotImplementedError</span></code></a></p>
<p>If a specific function, e.g. by the user is not implemented</p>
<dl class="py attribute">
<dt id="zfit.util.exception.SpecificFunctionNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.SpecificFunctionNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.SpecificFunctionNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.SpecificFunctionNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.MinimizeNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">MinimizeNotImplementedError</code><span class="sig-paren">(</span><em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#MinimizeNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.MinimizeNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.FunctionNotImplementedError" title="zfit.util.exception.FunctionNotImplementedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.FunctionNotImplementedError</span></code></a></p>
<p>The <cite>minimize</cite> function of a minimizer is not implemented.</p>
<dl class="py attribute">
<dt id="zfit.util.exception.MinimizeNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.MinimizeNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.MinimizeNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.MinimizeNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.MinimizeStepNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">MinimizeStepNotImplementedError</code><span class="sig-paren">(</span><em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#MinimizeStepNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.MinimizeStepNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.FunctionNotImplementedError" title="zfit.util.exception.FunctionNotImplementedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.FunctionNotImplementedError</span></code></a></p>
<p>The <cite>step</cite> function of a minimizer is not implemented.</p>
<dl class="py attribute">
<dt id="zfit.util.exception.MinimizeStepNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.MinimizeStepNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.MinimizeStepNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.MinimizeStepNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.AnalyticNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">AnalyticNotImplementedError</code><span class="sig-paren">(</span><em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#AnalyticNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.AnalyticNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.ZfitNotImplementedError" title="zfit.util.exception.ZfitNotImplementedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.ZfitNotImplementedError</span></code></a></p>
<p>General exception if an analytic way is not implemented</p>
<dl class="py attribute">
<dt id="zfit.util.exception.AnalyticNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.AnalyticNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.AnalyticNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.AnalyticNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.AnalyticIntegralNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">AnalyticIntegralNotImplementedError</code><span class="sig-paren">(</span><em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#AnalyticIntegralNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.AnalyticIntegralNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.AnalyticNotImplementedError" title="zfit.util.exception.AnalyticNotImplementedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.AnalyticNotImplementedError</span></code></a></p>
<p>If an analytic integral is not provided.</p>
<dl class="py attribute">
<dt id="zfit.util.exception.AnalyticIntegralNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.AnalyticIntegralNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.AnalyticIntegralNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.AnalyticIntegralNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.AnalyticSamplingNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">AnalyticSamplingNotImplementedError</code><span class="sig-paren">(</span><em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#AnalyticSamplingNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.AnalyticSamplingNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference internal" href="#zfit.util.exception.AnalyticNotImplementedError" title="zfit.util.exception.AnalyticNotImplementedError"><code class="xref py py-class docutils literal notranslate"><span class="pre">zfit.util.exception.AnalyticNotImplementedError</span></code></a></p>
<p>If analytic sampling from a distribution is not possible.</p>
<dl class="py attribute">
<dt id="zfit.util.exception.AnalyticSamplingNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.AnalyticSamplingNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.AnalyticSamplingNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.AnalyticSamplingNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.NormRangeNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">NormRangeNotImplementedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#NormRangeNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.NormRangeNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<p>Indicates that a function does not support the normalization range argument <cite>norm_range</cite>.</p>
<dl class="py attribute">
<dt id="zfit.util.exception.NormRangeNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.NormRangeNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.NormRangeNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.NormRangeNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.MultipleLimitsNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">MultipleLimitsNotImplementedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#MultipleLimitsNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.MultipleLimitsNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<p>Indicates that a function does not support several limits in a <a class="reference internal" href="zfit.html#zfit.Space" title="zfit.Space"><code class="xref py py-class docutils literal notranslate"><span class="pre">Space</span></code></a>.</p>
<dl class="py attribute">
<dt id="zfit.util.exception.MultipleLimitsNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.MultipleLimitsNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.MultipleLimitsNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.MultipleLimitsNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.VectorizedLimitsNotImplementedError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">VectorizedLimitsNotImplementedError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#VectorizedLimitsNotImplementedError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.VectorizedLimitsNotImplementedError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<p>Indicates that a function does not support vectorized (n_events &gt; 1) limits in a <a class="reference internal" href="zfit.html#zfit.Space" title="zfit.Space"><code class="xref py py-class docutils literal notranslate"><span class="pre">Space</span></code></a>.</p>
<dl class="py attribute">
<dt id="zfit.util.exception.VectorizedLimitsNotImplementedError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.VectorizedLimitsNotImplementedError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.VectorizedLimitsNotImplementedError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.VectorizedLimitsNotImplementedError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.WorkInProgressError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">WorkInProgressError</code><a class="reference internal" href="../_modules/zfit/util/exception.html#WorkInProgressError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.WorkInProgressError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<p>Only for developing purpose! Does not serve as a ‘real’ Exception.</p>
<dl class="py attribute">
<dt id="zfit.util.exception.WorkInProgressError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.WorkInProgressError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.WorkInProgressError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.WorkInProgressError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.BreakingAPIChangeError">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">BreakingAPIChangeError</code><span class="sig-paren">(</span><em class="sig-param"><span class="n">msg</span></em>, <em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#BreakingAPIChangeError"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.BreakingAPIChangeError" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.BreakingAPIChangeError.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.BreakingAPIChangeError.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.BreakingAPIChangeError.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.BreakingAPIChangeError.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt id="zfit.util.exception.BehaviorUnderDiscussion">
<em class="property">exception </em><code class="sig-prename descclassname">zfit.util.exception.</code><code class="sig-name descname">BehaviorUnderDiscussion</code><span class="sig-paren">(</span><em class="sig-param"><span class="n">msg</span></em>, <em class="sig-param"><span class="o">*</span><span class="n">args</span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/zfit/util/exception.html#BehaviorUnderDiscussion"><span class="viewcode-link">[source]</span></a><a class="headerlink" href="#zfit.util.exception.BehaviorUnderDiscussion" title="Permalink to this definition">¶</a></dt>
<dd><p>Bases: <a class="reference external" href="https://docs.python.org/3/library/exceptions.html#Exception" title="(in Python v3.9)"><code class="xref py py-class docutils literal notranslate"><span class="pre">Exception</span></code></a></p>
<dl class="py attribute">
<dt id="zfit.util.exception.BehaviorUnderDiscussion.args">
<code class="sig-name descname">args</code><a class="headerlink" href="#zfit.util.exception.BehaviorUnderDiscussion.args" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

<dl class="py method">
<dt id="zfit.util.exception.BehaviorUnderDiscussion.with_traceback">
<code class="sig-name descname">with_traceback</code><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#zfit.util.exception.BehaviorUnderDiscussion.with_traceback" title="Permalink to this definition">¶</a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

</div>


              </div>
              
              
              <div class='prev-next-bottom'>
                

              </div>
              
          </main>
          

      </div>
    </div>

    
  <script src="../_static/js/index.3da636dd464baa7582d2.js"></script>


    <footer class="footer mt-5 mt-md-0">
  <div class="container">
    <p>
          &copy; Copyright Copyright 2018, zfit.<br/>
        Created using <a href="http://sphinx-doc.org/">Sphinx</a> 3.3.0.<br/>
    </p>
  </div>
</footer>
  </body>
</html>